### ISSUE TITLE
Jumper disappears after restarting XCode

### ISSUE THREAD

**Issue by obuseme** [deszip/Jumper#1]
I'm using the latest version available through Alcatraz, and any time I restart XCode, the two Jumper menu items disappear from the Edit menu in XCode, even though Alcatraz still shows Jumper as installed.  Reinstalling Jumper fixes the problem, but annoying to do that every XCode restart.  How can I help get this fixed?

**Comment by AdamsMi** [comment]
Actually, this is still the case ;/
